spring:
  datasource:
    url: jdbc:h2:mem:tradeengine;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
app:
  strategies:
    - name: DOUBLE_DIVERGENCE_STRATEGY
      enabled: false
      timeframes: [ H1, H4, D1 ]
    - name: FVG_KEYLEVEL_DIVERGENCE_STRATEGY
      enabled: true
      timeframes: [ M5, M15, H1, H4 ]
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}
server:
  port: 8081