spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trade_engine_db
    driver-class-name: org.postgresql.Driver
    username: trade_user
    password: 2137Leman2137!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
app:
  telegram:
    bot-token: "7343099757:AAFr8AUBIzdEnLXjY8mfIBYmrftTuDrMfm0"
    chat-id: "5040904527"