spring:
  application:
    version: "1.1.0"
  profiles:
    active: dev
logging:
  level:
    root: INFO
    pl.tradeengine.backtest: DEBUG

  h2:
    console:
      enabled: true
      path: /h2-console
