spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
app:
  strategies:
    - name: DOUBLE_DIVERGENCE_STRATEGY
      enabled: true
      timeframes: [ H1, H4, D1 ]
    - name: FVG_KEYLEVEL_DIVERGENCE_STRATEGY
      enabled: false
      timeframes: [ H1, H4 ]
    - name: "GRINDER_SWING_D1_H1"
      enabled: true
      timeframes: [ H1 ]
    - name: "GRINDER_POSITION_W1_H4"
      enabled: true
      timeframes: [ H4 ]
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}